applicaster-plugins/Zee5PlayerPlugin-iOS

Manifest/zapp_manifest.json, PluginClasses/HybridScreen/HybridViewController+Subviews.swift, Zee5PlayerPlugin.podspec
=> add download button func

PluginClasses/HybridScreen/HybridViewController.xib, PluginClasses/ZEE5PlayerSDK/AddToWatchlist/AddToWatchlist.m, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine+AppsFlyer.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine.swift, PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/DownloadQuality/DownloadQualityMenu.swift, PluginClasses/ZEE5PlayerSDK/Download UI/EmptyView.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowsDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/Utils/Utility.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDelegate.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/Zee5DownloadManager.swift, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5PluggablePlayer.swift, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
=> New- dev- branch

PluginClasses/HybridScreen/HybridViewController.swift
=> Download btn

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
PlayBack rate and, Progress bar Issue
=> ZNA-4874 ,ZNA-4893

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/ZEE5PlayerSDK/Zee5Slider/Zee5Slider.m
Slider Touch add, Telco Action, Previous Callback added, Live News Added
=> ZNA-5004,ZNA-4860,ZNA-4853

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/NetworkManager/BaseUrls.h, PluginClasses/ZEE5PlayerSDK/NetworkManager/BaseUrls.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
Internet check, Vod Token(nonDRM),WatchHistory
=> ZNA-5116,ZNA-5111,ZNA-5036,ZNA-4930,ZNA-4866

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/ZappZee5PlayerAdapter.swift, PluginClasses/ZEE5PlayerSDK/Download UI/DownloadQuality/DownloadQualityMenu.swift, PluginClasses/ZEE5PlayerSDK/Download UI/MovieDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowDetailController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/VideoDownloadController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5Resources/Download.storyboard, PluginClasses/Zee5Resources/DownloadQualityMenu.xib, PluginClasses/Zee5Resources/OfflinePlayerController.xib
ZNA-5417,ZNA-5375,ZNA-5441,ZNA-5364, ZNA-5244,ZNA-4930
=> Offline Video Mode, Quality Selection In Landscape, add Changes

Manifest/zapp_manifest.json, PluginClasses/Helpers/Actions/WatchListActionButtonBuilder.swift, Specs/Zee5PlayerPlugin/1.1.15/Zee5PlayerPlugin.podspec
[ZNA-4862](https://asiatvusa.atlassian.net/browse/ZNA-4862)
Watchlist added and Removed toast message fails to display post adding any content to Watchlist screen. 
Fix: Adding toast messages showing.
=> Watchlist - Watchlist add and remove toast message

PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Utility/Utility.h, PluginClasses/ZEE5PlayerSDK/Utility/Utility.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
ZNA-5455, ZNA-5432, ZNA-5431, ZNA-5430, ZNA-4873, ZNA-5346, ZNA-4777, ZNA-5415
=> Local Storage Changed, Handle crash, Add Count

PluginClasses/ZEE5PlayerSDK/PlayerManager/Zee5FanAdManager/Zee5FanAdManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/Zee5FanAdManager/Zee5FanAdManager.m
=> Fb audience branch

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass+PlayerEvents.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass+appsfly+qgraph.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine+AppsFlyer.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/ConvivaAnalytics.swift, PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/Zee5iOSPlayerPlugin.swift, PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.h, PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/CurrentItem.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5PlayerSDK.h, PluginClasses/ZEE5PlayerSDK/ZEE5PlayerSDK.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/Zee5DownloadManager.swift, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.h, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5PluggablePlayer.swift
=> Conviva ,appsflyer,Qgraph,Mixpannel

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine+AppsFlyer.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/Zee5DownloadManager.swift, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.h, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
Download Delete, and subscribe view on Player
=> ZNA-5176,ZNA-6110

PluginClasses/ZEE5PlayerSDK/Download UI/CustomCells/DownloadTableCell.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowsDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/Utils/DownloadItem.swift, PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.h, PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.m, PluginClasses/ZEE5PlayerSDK/NetworkManager/BaseUrls.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/CurrentItem.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DB/DownloadDataItem.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DB/ZeeDownloadDatabase.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift
=> New changes (Blockers)

PluginClasses/Helpers/Actions/DownloadActionButtonBuilder.swift, PluginClasses/ZEE5PlayerSDK/Download UI/DownloadQuality/DragableView.swift, PluginClasses/ZEE5PlayerSDK/Download UI/EditDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/MovieDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowDetailController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/Utils/DownloadItem.swift, PluginClasses/ZEE5PlayerSDK/Download UI/VideoDownloadController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/CurrentItem.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DB/DownloadDataItem.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DB/ZeeDownloadDatabase.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift, PluginClasses/ZEE5PlayerSDK/popUpViews/ParentalView/ParentalView.m, PluginClasses/Zee5PluggablePlayer.swift, PluginClasses/Zee5Resources/OfflinePlayerController.xib
Offline Video playBack Parental Control Add
=> Offline parental Control add

PluginClasses/ZEE5PlayerSDK/Model/TvShowModel/tvShowModel.h, PluginClasses/ZEE5PlayerSDK/Model/TvShowModel/tvShowModel.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5PlayerSDK.m
=> Tv Show Model Changed and Content Click Api Removed

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Companion Ads fetch in Player

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Content id changed notification

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Midroll handled

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/Zee5PlayerPlugin.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m, PluginClasses/ZEE5PlayerSDK/Utility/ZEE5UserDefaults.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Live News. Accees token Error handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/Zee5PluggablePlayer.swift
=> Zna 4722dev

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m
=> WatchlistApiChanges

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
ZNA-6498   MOAt Obstruction handled in Ads
=> Moat View obstruction Handled

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift
=> Crash Handle of Offline Player

Manifest/zapp_manifest.json, PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/GestureHandlerHelper.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/GestureHandlerHelper.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5PluggablePlayer.swift, Specs/Zee5PlayerPlugin/1.1.38/Zee5PlayerPlugin.podspec, Zee5PlayerPlugin.xcodeproj/project.pbxproj
Gesture Handler Helper class helps handle situation when on player ads is being shown but we try to close player by pan-down-move gesture
=> ZNA-6197 - [IMD] - Player - User is unable to close the player by swiping down during content playback.

Manifest/zapp_manifest.json, PluginClasses/ZEE5PlayerSDK/PlayerManager/GestureHandlerHelper.m, Specs/Zee5PlayerPlugin/1.1.39/Zee5PlayerPlugin.podspec
If app in landscape mode, there is a functionality of opening and closing next video carousels by swiping up and down.
Disable closing player if in landscape mode by swiping down move.
=> ZNA-6503 - [IMD] - Player - User is unable to close the player by swiping down during content playback.

PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> ZNA-6612 ,Debug Mode  and  log level Added

PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Request TimeOut Interval Set

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Blank Screen handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
ZNA-6702(Auto Play  Off Handled)
=> Auto Playoff Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Loader handled

Manifest/zapp_manifest.json, PluginClasses/Helpers/Actions/WatchListActionButtonBuilder.swift, Specs/Zee5PlayerPlugin/1.1.43/Zee5PlayerPlugin.podspec
https://asiatvusa.atlassian.net/browse/ZNA-4705 * updated version
=> fix: fixed ZNA-4705

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-6749 (Moat View Obstruction and PlayBackView)
=> MoatView Changes And PlayBackViewAlloc

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> skip next and Skip previous in Live handled

PluginClasses/ZEE5PlayerSDK/Download UI/DownloadRootController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/MovieDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowsDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/VideoDownloadController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift
=> DownloadSession and Expired Download Handled

PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Debug Mode Removed

PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.h, PluginClasses/ZEE5PlayerSDK/Model/ZEE5VodDataModel/VODContentDetailsDataModel.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/CurrentItem.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
Post Login Subscribe View handled
=> PostLogin Method Added

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/Zee5PluggablePlayer.swift, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
=> Telco Changes

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Trailer FollowBack changes

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.h, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/Zee5Resources/ParentalView.xib, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
ZNA-7047,ZNA-6984,ZNA-6986,ZNA-7106,ZNA-6151
=> parental view And AdultView Logic changed

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.h, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Ad Playback pause handled

Manifest/zapp_manifest.json, PluginClasses/Helpers/Actions/ActionBarHelper.swift, PluginClasses/HybridScreen/HybridViewController+Subviews.swift, Specs/Zee5PlayerPlugin/1.1.49/Zee5PlayerPlugin.podspec
complete implementation as in android part
=> Download icon fails to display for Zee5 Originals shows

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift
=> Ad PlayBack Pause

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Slider Reset

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> External Subtitle Comment

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> For Regional pack user handled Condition

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift
=> Rotation Handled OfflineVideo

PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController+PlayerDisplayMode.swift
=> Share Menu Play Pause Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-7266   Ad countinue handled in Premium handled
=> Non trailer Premium content handled

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> navigate Back From login and Subscribe  handled

Manifest/zapp_manifest.json, PluginClasses/Helpers/Actions/WatchListActionButtonBuilder.swift, Specs/Zee5PlayerPlugin/1.1.56/Zee5PlayerPlugin.podspec
ticket https://asiatvusa.atlassian.net/browse/ZNA-6255
=> fix: added header to watchlist request

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass+appsfly+qgraph.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerDeeplinkManager.swift
=> Anlytics 7065

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> SkipPreVious CTA Logic Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Yellow Line Removed

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Parental On Click of Download Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Loader When Seeked

PluginClasses/ZEE5PlayerSDK/popUpViews/ParentalView/ParentalView.m
=> Parental Pin Enter Issue

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/popUpViews/ParentalView/ParentalView.m
=> Offline Forgot Pin Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.h, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
=> Touchable Button  Menu View hidden For Live.

PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m
=> first time Screen Orientation, and Touchable Button

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/Zee5PluggablePlayer.swift
=> Gloabal Ads , One Trust

PluginClasses/ZEE5PlayerSDK/Download UI/CustomCells/DownloadOptionCell.swift, PluginClasses/ZEE5PlayerSDK/Download UI/CustomCells/DownloadTableCell.swift, PluginClasses/ZEE5PlayerSDK/Download UI/CustomCells/NewEpisodeDownloadCell.swift, PluginClasses/ZEE5PlayerSDK/Download UI/DownloadRootController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/EditDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/EmptyView.swift, PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowDetailController.swift, PluginClasses/ZEE5PlayerSDK/Helpers/PlayerConstants.swift, PluginClasses/Zee5Resources/Download.storyboard, PluginClasses/Zee5Resources/EmptyView.xib
ZNA-7452 (Translation added in Downloads)
=> Downloads Translation Added

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
on Before Tv Show, Hybrid Screen Need to show
=> BeforeTv Hybrid Screen

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Parental Changes

PluginClasses/ZEE5PlayerSDK/Model/ZeePlayble.swift
=> Shows Playback code.

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Login Succees CallBack

PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m
=> telco Back to Vodafone Action

PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m
ZNA-7336 (Watch History Change)
=> Watch history Change

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Btn Skip Next Changes

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-6971(Auto play For guest and registred)
=> auto play for guest and registred user

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Conviva param Change

PluginClasses/ZEE5PlayerSDK/Model/ZeePlayble.swift
Call Back If no Episode we get (ZNA-8013)
=> Episode Null Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> next Button Loop avoid

PluginClasses/Zee5Resources/ZEE5CustomControl.xib
telco back to partner Change ZNA-7921
=> Telco back To partner App

PluginClasses/Zee5Resources/Download.storyboard
=> Progress bar

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Live Loader Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> PlayBackrate

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Playback rate and menu button in Offline Donload

PluginClasses/Zee5Resources/ParentalView.xib
=> Remove button text

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-7989(Pinch To Zoom functionality)
=> Pinch To Zoom

PluginClasses/ZEE5PlayerSDK/DeviceManager/DeviceManager.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> device maxout Error

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
Zna-7039(Restore Download Crash)
=> RestoreDownload Crash

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.h, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/Zee5CollectionCell/Zee5CollectionCell.m, PluginClasses/Zee5Resources/ZEE5CustomControl.xib, PluginClasses/Zee5Resources/Zee5CollectionCell.xib
Related Content Show in Player Landscape(ZNA-8137)
=> Related Content Show in Landscape

PluginClasses/HybridScreen/HybridViewController+FeedType.swift
ticket: https://asiatvusa.atlassian.net/browse/ZNA-8119
=> fix: fixed ZNA-8119

PluginClasses/Helpers/Actions/WatchListActionButtonBuilder.swift, PluginClasses/ZEE5PlayerSDK/AddToWatchlist/AddToWatchlist.m
ZNA-8283(Watchlist Success Callback)
=> Wtachlist callback

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Parental control FallBack

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Downloads option

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m
=> Watch Credit

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-5836(Parental Control for 18++)
=> Parental Control for 18++

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> rsVod user Call Back

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/Zee5Resources/OfflinePlayerController.xib
Zna-5490,ZNA-5830(replay and orientation)
=> Replay Added in OfflineDownload

PluginClasses/ZEE5PlayerSDK/Download UI/MovieDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowDetailController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/VideoDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/Zee5DownloadManager.swift
=> Restore Download

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/NetworkManager/NetworkManager.h, PluginClasses/ZEE5PlayerSDK/NetworkManager/NetworkManager.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.h, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m, PluginClasses/Zee5Resources/ZEE5CustomControl.xib
ZNA-8375 (Watch Credit And Reporting Manager)
=> Reporting manger Changed And Watch credit

PluginClasses/ZEE5PlayerSDK/Download UI/DownloadQuality/DownloadQualityMenu.swift
=> Quality Selection Btn Action

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5PlayerSDK.m
=> Login Callback

PluginClasses/ZEE5PlayerSDK/popUpViews/ParentalView/ParentalView.m
=> Parental pin Enter Changes

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> CalBack for Registerd User

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-7847(Player controls between two ads)
=> Player Controls between two ads

PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
ZNA-8591(Midroll Moat Obstruction)
=> Moat Obstruction , Player Loader handled at midroll

PluginClasses/ZEE5PlayerSDK/NetworkManager/NetworkManager.m, PluginClasses/ZEE5PlayerSDK/ReportingManager/ReportingManager.m
ZNA-8375(Playback Complete delete From Watch History)
=> Delete Watch History Api

PluginClasses/ZEE5PlayerSDK/Download UI/CustomCells/DownloadOptionCell.swift
Resume and cancel items in Downloaded Page
=> Downloaded Page - Resume and cancel items

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/Zee5CollectionCell/Zee5CollectionCell.m, PluginClasses/Zee5Resources/Zee5CollectionCell.xib
=> UpNext Changes

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass+PlayerEvents.swift
=> GA Event Count

PluginClasses/Helpers/PartnerAppHelper.swift, PluginClasses/HybridScreen/HybridViewController+Subviews.swift, PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/HybridScreen/Xibs/HybridViewController.xib, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.h, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/ZEE5CustomControl.m, PluginClasses/Zee5PluggablePlayer.swift, PluginClasses/Zee5Resources/ZEE5CustomControl.xib, Zee5PlayerPlugin.xcodeproj/project.pbxproj
ZNA-8596(telco Design Moved to consumption)
=> Telco Design Added in Consumption Screen

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Conviva Playername

PluginClasses/ZEE5PlayerSDK/CdnHandler/CdnHandler.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-3016 (cdn Api Param add in Url)
=> Cdn Api changes

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> LiveTv Crash

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift
Offline and onlinePlaybackrate
=> Playback rate Handled

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
ZNA-9017,ZNA-6620 (postroll Ad issue)
=> post-Roll Add Issue

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Error Info Message conviva

PluginClasses/ZEE5PlayerSDK/Download UI/MovieDownloadController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/ShowDetailController.swift, PluginClasses/ZEE5PlayerSDK/Download UI/VideoDownloadController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift
ZNA-9101 (Non-drm Video Download)
=> Non-Drm Video Download Error

PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Info Message for conviva

PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
=> Ad Count issue

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.h, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5CustomControl/TouchableButton.swift, PluginClasses/Zee5Resources/OfflinePlayerController.xib
=> Offline touchable button

PluginClasses/Helpers/Actions/WatchListActionButtonBuilder.swift, PluginClasses/ZEE5PlayerSDK/AddToWatchlist/AddToWatchlist.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Playback check

PluginClasses/Helpers/Actions/ActionBarHelper.swift, PluginClasses/Helpers/Consts.swift, PluginClasses/ZEE5PlayerSDK/Model/ZeePlayble.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/DownloadHelper.swift, PluginClasses/ZEE5PlayerSDK/Zee5DownloadManager/Zee5DownloadManager.swift
ZNA-9263(Bitrate url Change and Non-Drm Download)
=> Bitrate Url changes and Non Drm Download

PluginClasses/ZEE5PlayerSDK/NetworkManager/BaseUrls.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
(ZNA-5320)Intenational Production Ad Api changed
=> International Production Ad Changed

PluginClasses/ZEE5PlayerSDK/ApplicasterPlayerPlugin/KalturaPlayerController.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-9267 (App minimize playback While hybridview Open)
=> App Minimize playback

PluginClasses/ZEE5PlayerSDK/Download UI/OfflinePlayerController.swift
ZNA-8745(Downloads Background,ForeGround)
=> Background ,Foreground handled in Downloads

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/ConvivaAnalytics.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.h, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m, PluginClasses/ZEE5PlayerSDK/ZEE5PlayerSDK.h, PluginClasses/ZEE5PlayerSDK/Zee5PlayerPlugin/Zee5PlayerPlugin.m
ZNA-9505,ZNA-9230(Conviva And Playback)
=> Conviva and Drm fallback Handled

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass.swift
=> Language short Code Analytics

PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass+PlayerEvents.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AllAnalyticsClass.swift, PluginClasses/ZEE5PlayerSDK/AnalyticsManager/AnalyticEngine.swift, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
ZNA-9406 (video clicked Analytics Add)
=> Video Click Analytics Added

PluginClasses/Helpers/Actions/ActionButtonBuilder.swift, PluginClasses/Helpers/Actions/TrailerActionButtonBuilder.swift, PluginClasses/HybridScreen/HybridViewController+Subviews.swift, PluginClasses/HybridScreen/HybridViewController.swift, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.h, PluginClasses/ZEE5PlayerSDK/Helpers/SingletonClass.m, PluginClasses/ZEE5PlayerSDK/PlayerManager/ZEE5PlayerManager.m
=> Premium Banner Logic Changed
